apiVersion: v1
kind: Pod
metadata:
        name: memory-demo
        namespace: firstnamespace
spec:
        containers:
                - name: memory-demo
                  image: polinux/stress
                  resources:
                          limits:
                                  memory: "200Mi"
                          requests:
                                  memory: "100Mi"
                  command: ["stress"]
                  args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
