apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-Deployment
  label:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
  spec:
    containers:
      - name: nginx-container
        image: nginx
  replicas: 6

  selector:
    matchLabels:
      app: myapp
