apiVersion: v1

kind: Pod

metadata:
        name: myapp-pod
        labels:
                app: myapp
                cost: Iwill
                location: aisa
                price: accha
spec:
        containers:
                - name: nginx-container
                  image: nginx
